[package]
name = "os"
version = "0.1.0"
edition = "2024"

[profile.release]
debug = true
opt-level = 0           # 优化级别,最低是0,最高是3, 0方便debug
overflow-checks = false # 关闭整数溢出检查

[dependencies]
sbi-rt = { version = "0.0.3", features = ["legacy"] }
